/*
 * SPDX-FileCopyrightText: 2026 namailu.cz
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-SEL
 */

//! Fork change: mail that a *user* Sieve script sends out (`redirect`, `vacation`,
//! `notify`) asks the RCPT-stage MTA hook first, exactly like a recipient added in an
//! SMTP/JMAP submission would.
//!
//! Upstream queues these messages directly, without an SMTP session, so no MTA hook,
//! milter or rate limit ever sees them. An operator enforcing per-account sending limits
//! in the hook is then bypassed by a one-line Sieve filter (or by the account's own
//! forwarding), and the redirected mail leaves from the operator's IP.
//!
//! The request mimics an RCPT hook call: `context.stage = "rcpt"`, `context.sasl.login`
//! is the account, the envelope is the account → the target. An extra `context.sieve`
//! says whether this is a redirect of the received message (`"redirect"`) or a message
//! the script created (`"message"`: vacation, notify), so the hook can apply different
//! rules to each.
//!
//! Failure is closed: a hook error, a timeout or anything but `"action": "accept"` drops
//! the outgoing copy. The existing original-message inbox fallback remains, but
//! generated replies are not durably retried and may be lost on scanner failure.
//!
//! Missing RCPT or DATA protection fails closed for outgoing Sieve copies.

use common::{Server, config::smtp::session::Stage};
use std::time::Duration;
use trc::SieveEvent;
use utils::HttpLimitResponse;

/// The hook runs inside local delivery; do not hold it for the full SMTP hook timeout.
const MAX_WAIT: Duration = Duration::from_secs(10);

/// Scan the final generated bytes, without repeating RCPT quota reservations.
/// Missing DATA protection, errors and non-accept decisions are fail-closed.
pub(crate) async fn sieve_data_allowed(
    server: &Server,
    account: &str,
    recipients: &[String],
    raw: &[u8],
) -> Option<Vec<u8>> {
    tokio::time::timeout(MAX_WAIT,
        sieve_data_allowed_inner(server, account, recipients, raw))
        .await.ok().flatten()
}

async fn sieve_data_allowed_inner(
    server: &Server,
    account: &str,
    recipients: &[String],
    raw: &[u8],
) -> Option<Vec<u8>> {
    let Some(hook) = server.core.smtp.session.hooks.iter()
        .find(|hook| hook.run_on_stage.contains(&Stage::Data)) else { return None; };
    let score = super::outgoing_spam::score_generated(server, account, recipients, raw)
        .await.ok()?;
    let server_headers = score.map(|(score, tags)| vec![
        ("X-Spam-Score", format!("{score:.2}")),
        ("X-Spam-Tags", tags),
    ]).unwrap_or_default();
    let mut encoded = Vec::new();
    if mail_builder::encoders::Base64Encoder::new().encode_to_writer(raw, &mut encoded).is_err() {
        return None;
    }
    let Ok(encoded) = String::from_utf8(encoded) else { return None; };
    let body = serde_json::json!({
        "context": {"stage": "data", "sasl": {"login": account}, "sieve": "message"},
        "envelope": {"from": {"address": account}, "to": recipients.iter()
            .map(|address| serde_json::json!({"address": address})).collect::<Vec<_>>()},
        "message": {"rawBase64": encoded, "serverHeaders": server_headers}
    });
    let Ok(response) = hook.client.post(&hook.url)
        .timeout(hook.timeout.min(MAX_WAIT)).headers(hook.headers.clone())
        .body(body.to_string()).send().await else { return None; };
    if !response.status().is_success() { return None; }
    match response.bytes_with_limit(hook.max_response_size).await {
        Ok(Some(bytes)) => serde_json::from_slice::<serde_json::Value>(&bytes)
            .ok().and_then(|value| apply_scan_headers(raw, &value)),
        _ => None,
    }
}

/// Only scanner-owned header edits are permitted; never rewrite the body/envelope.
fn apply_scan_headers(raw: &[u8], verdict: &serde_json::Value) -> Option<Vec<u8>> {
    if verdict.get("action")?.as_str()? != "accept" { return None; }
    let mut output = Vec::with_capacity(raw.len() + 128);
    let mut skip = false;
    let mut offset = 0;
    let mut body_offset = None;
    for line in raw.split_inclusive(|byte| *byte == b'\n') {
        offset += line.len();
        if line == b"\r\n" || line == b"\n" {
            body_offset = Some(offset);
            break;
        }
        if !line.starts_with(b" ") && !line.starts_with(b"\t") {
            let colon = line.iter().position(|byte| *byte == b':')?;
            let name = std::str::from_utf8(&line[..colon]).ok()?;
            skip = name.eq_ignore_ascii_case("X-Namailu-Scan-Status")
                || name.eq_ignore_ascii_case("X-Namailu-Scan-Engine");
        }
        if !skip { output.extend_from_slice(line); }
    }
    let mut added_status = false;
    let mut added_engine = false;
    for modification in verdict.get("modifications")?.as_array()? {
        let name = modification.get("name")?.as_str()?;
        if !name.eq_ignore_ascii_case("X-Namailu-Scan-Status")
            && !name.eq_ignore_ascii_case("X-Namailu-Scan-Engine") { return None; }
        match modification.get("type")?.as_str()? {
            "deleteHeader" => {},
            "addHeader" => {
                let value = modification.get("value")?.as_str()?;
                if name.eq_ignore_ascii_case("X-Namailu-Scan-Status") {
                    if added_status || !matches!(value,
                        "clean" | "unscannable_encrypted" | "unscannable_archive") {
                        return None;
                    }
                    added_status = true;
                } else {
                    if added_engine || value != "clamav" { return None; }
                    added_engine = true;
                }
                output.extend_from_slice(format!("{name}: {value}\r\n").as_bytes());
            },
            _ => return None,
        }
    }
    if !added_status || !added_engine { return None; }
    output.extend_from_slice(b"\r\n");
    output.extend_from_slice(&raw[body_offset?..]);
    Some(output)
}

#[cfg(test)]
mod tests {
    use super::apply_scan_headers;

    #[test]
    fn final_scan_headers_replace_forgery_without_changing_binary_body() {
        let raw = b"Subject: final\r\nX-Namailu-Scan-Status: clean\r\n forged\r\n\r\nbody\xff";
        let verdict = serde_json::json!({"action": "accept", "modifications": [
            {"type": "deleteHeader", "name": "X-Namailu-Scan-Status", "index": 1},
            {"type": "addHeader", "name": "X-Namailu-Scan-Status", "value": "unscannable_encrypted"},
            {"type": "addHeader", "name": "X-Namailu-Scan-Engine", "value": "clamav"}
        ]});
        let output = apply_scan_headers(raw, &verdict).unwrap();
        assert_eq!(output, b"Subject: final\r\nX-Namailu-Scan-Status: unscannable_encrypted\r\nX-Namailu-Scan-Engine: clamav\r\n\r\nbody\xff");
    }

    #[test]
    fn unsafe_modifications_and_nonaccept_are_closed() {
        let raw = b"Subject: final\r\n\r\nbody";
        for verdict in [
            serde_json::json!({"action": "reject", "modifications": []}),
            serde_json::json!({"action": "accept", "modifications": []}),
            serde_json::json!({"action": "accept", "modifications": [
                {"type": "addRecipient", "value": "attacker@example.test"}]}),
            serde_json::json!({"action": "accept", "modifications": [
                {"type": "addHeader", "name": "X-Namailu-Scan-Status", "value": "clean\r\nInjected: yes"}]})
        ] {
            assert!(apply_scan_headers(raw, &verdict).is_none());
        }
    }

    #[test]
    fn fresh_scanner_proof_requires_both_unique_known_headers() {
        let raw = b"Subject: final\r\n\r\nbody";
        let status = serde_json::json!({"type": "addHeader",
            "name": "X-Namailu-Scan-Status", "value": "clean"});
        let engine = serde_json::json!({"type": "addHeader",
            "name": "X-Namailu-Scan-Engine", "value": "clamav"});
        for modifications in [
            vec![status.clone()],
            vec![engine.clone()],
            vec![status.clone(), status.clone(), engine.clone()],
            vec![status.clone(), engine.clone(), engine.clone()],
            vec![serde_json::json!({"type": "addHeader",
                "name": "X-Namailu-Scan-Status", "value": "suspicious"}), engine.clone()],
            vec![status.clone(), serde_json::json!({"type": "addHeader",
                "name": "X-Namailu-Scan-Engine", "value": "untrusted"})],
        ] {
            assert!(apply_scan_headers(raw, &serde_json::json!({
                "action": "accept", "modifications": modifications})).is_none());
        }
        assert!(apply_scan_headers(raw, &serde_json::json!({
            "action": "accept", "modifications": [status, engine]})).is_some());
    }
}

pub(crate) async fn sieve_outbound_allowed(
    server: &Server,
    account: &str,
    recipient: &str,
    is_redirect: bool,
    session_id: u64,
) -> bool {
    let Some(hook) = server
        .core
        .smtp
        .session
        .hooks
        .iter()
        .find(|hook| hook.run_on_stage.contains(&Stage::Rcpt))
    else {
        return false;
    };

    let body = serde_json::json!({
        "context": {
            "stage": "rcpt",
            "sasl": { "login": account },
            "sieve": if is_redirect { "redirect" } else { "message" },
        },
        "envelope": {
            "from": { "address": account },
            "to": [ { "address": recipient } ],
        },
    });

    let verdict = match hook
        .client
        .post(&hook.url)
        .timeout(hook.timeout.min(MAX_WAIT))
        .headers(hook.headers.clone())
        .body(body.to_string())
        .send()
        .await
    {
        Ok(response) if response.status().is_success() => {
            match response.bytes_with_limit(hook.max_response_size).await {
                Ok(Some(bytes)) => serde_json::from_slice::<serde_json::Value>(&bytes)
                    .ok()
                    .and_then(|value| {
                        value
                            .get("action")
                            .and_then(|action| action.as_str())
                            .map(|action| action == "accept")
                    })
                    .ok_or("invalid hook response"),
                Ok(None) => Err("hook response too large"),
                Err(_) => Err("failed to read hook response"),
            }
        }
        Ok(_) => Err("hook returned an error status"),
        Err(_) => Err("hook request failed"),
    };

    match verdict {
        Ok(true) => true,
        Ok(false) => {
            trc::event!(
                Sieve(SieveEvent::QuotaExceeded),
                From = account.to_string(),
                To = recipient.to_string(),
                Details = "Outgoing Sieve message rejected by MTA hook.",
                SpanId = session_id
            );
            false
        }
        Err(reason) => {
            trc::event!(
                Sieve(SieveEvent::UnexpectedError),
                From = account.to_string(),
                To = recipient.to_string(),
                Details = reason,
                SpanId = session_id
            );
            false
        }
    }
}
