/*
 * SPDX-FileCopyrightText: 2026 namailu.cz
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-SEL
 */

//! Score final generated bytes using the same content policy as SMTP submission.
use common::Server;
use mail_parser::MessageParser;
use spam_filter::{
    SpamFilterInput,
    analysis::outgoing::{SIEVE_FORWARDING_TAGS, SpamFilterScoreOutgoing},
};

pub(crate) async fn score_generated(
    server: &Server,
    account: &str,
    recipients: &[String],
    raw: &[u8],
) -> Result<Option<(f32, String)>, ()> {
    let message = MessageParser::default().parse(raw).ok_or(())?;
    Ok(server.spam_score_outgoing_input(SpamFilterInput {
        message: &message,
        span_id: 0,
        arc_result: None,
        spf_ehlo_result: None,
        spf_mail_from_result: None,
        dkim_result: &[],
        dkim2_result: None,
        dmarc_result: None,
        dmarc_policy: None,
        iprev_result: None,
        remote_ip: std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST),
        ehlo_domain: None,
        authenticated_as: Some(account),
        asn: None,
        country: None,
        is_tls: false,
        env_from: account,
        env_from_flags: 0,
        env_rcpt_orig_to: recipients.iter().map(String::as_str).collect(),
        env_rcpt_rewritten_to: recipients.iter().map(String::as_str).collect(),
        is_test: false,
        is_train: false,
    }, SIEVE_FORWARDING_TAGS).await)
}
